name: clerk-service
services:
  reverse-proxy:
    image: nginx
    ports:
      - 4433:4433
    volumes:
      - ./etc/certs:/etc/nginx/certs
      - ./etc/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server

  server:
    build:
      context: .
      target: final
    ports:
      - 4000
